CREATE TABLE `alsfrs` (
`CommentID` varchar(255) NOT NULL default '',
                          `UserID` varchar(255) default NULL,
                          `Examiner` varchar(255) default NULL,
                          `Testdate` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                          `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL default 'Incomplete',
`Date_taken` date default NULL,
`Candidate_Age` varchar(255) default NULL,
`Window_Difference` varchar(255) default NULL,
`gastostomy` enum('','yes','no','not_answered') default NULL,
`speech` numeric default NULL,
`speech_status` enum('not_answered') default NULL,
`salivation` numeric default NULL,
`salivation_status` enum('not_answered') default NULL,
`swallowing` numeric default NULL,
`swallowing_status` enum('not_answered') default NULL,
`handwriting` numeric default NULL,
`handwriting_status` enum('not_answered') default NULL,
`cutting_no_gastrostomy` numeric default NULL,
`cutting_no_gastrostomy_status` enum('not_answered') default NULL,
`cutting_gastrostomy` numeric default NULL,
`cutting_gastrostomy_status` enum('not_answered') default NULL,
`dressing` numeric default NULL,
`dressing_status` enum('not_answered') default NULL,
`turning` numeric default NULL,
`turning_status` enum('not_answered') default NULL,
`walking` numeric default NULL,
`walking_status` enum('not_answered') default NULL,
`climbing` numeric default NULL,
`climbing_status` enum('not_answered') default NULL,
`dyspnea` numeric default NULL,
`dyspnea_status` enum('not_answered') default NULL,
`orthopnea` numeric default NULL,
`orthopnea_status` enum('not_answered') default NULL,
`repiratory` numeric default NULL,
`repiratory_status` enum('not_answered') default NULL,
`total` varchar(255) default NULL,
PRIMARY KEY  (`CommentID`)
);
REPLACE INTO test_names (Test_name, Full_name, Sub_group) VALUES ('alsfrs', 'ALSFRS-R Form', 1);
