CREATE TABLE `genetics` (
`CommentID` varchar(255) NOT NULL default '',
                          `UserID` varchar(255) default NULL,
                          `Examiner` varchar(255) default NULL,
                          `Testdate` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                          `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL default 'Incomplete',
`Date_taken` date default NULL,
`Candidate_Age` varchar(255) default NULL,
`Window_Difference` varchar(255) default NULL,
`form_type` enum('initial','update','no_change','not_answered') default NULL,
`als` enum('yes','no','not_answered') default NULL,
`mnd` enum('yes','no','not_answered') default NULL,
`a_m_other` text default NULL,
`dementia` enum('yes','no','not_answered') default NULL,
`ftd` enum('yes','no','not_answered') default NULL,
`alzheimers` enum('yes','no','not_answered') default NULL,
`f_a_other` text default NULL,
`psychiatric` enum('yes','no','not_answered') default NULL,
`p_other` text default NULL,
`notes_1` text default NULL,
`completed` enum('done','not_done') default NULL,
`genetic_date` date default NULL,
`mutation` enum('yes','no','not_answered') default NULL,
`genes` varchar(255) default NULL,
`other_genes` text default NULL,
`sequence` varchar(255) default NULL,
`lab_name` varchar(255) default NULL,
`note_2` text default NULL,
PRIMARY KEY  (`CommentID`)
);
REPLACE INTO test_names (Test_name, Full_name, Sub_group) VALUES ('genetics', 'Array', 1);
