CREATE TABLE `mef` (
`CommentID` varchar(255) NOT NULL default '',
                          `UserID` varchar(255) default NULL,
                          `Examiner` varchar(255) default NULL,
                          `Testdate` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                          `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL default 'Incomplete',
`Date_taken` date default NULL,
`Candidate_Age` varchar(255) default NULL,
`Window_Difference` varchar(255) default NULL,
`form_type` enum('initial','update','no_change','not_answered') default NULL,
`riluzole` enum('yes','no','not_answered') default NULL,
`riluzole_date` date default NULL,
`anticonvulsants` enum('yes','no','not_answered') default NULL,
`ac_medication` text default NULL,
`ac_medication_status` enum('not_answered') default NULL,
`psych_medications` enum('yes','no','not_answered') default NULL,
`p_medication` text default NULL,
`p_medication_status` enum('not_answered') default NULL,
`benzodiazepines` enum('yes','no','not_answered') default NULL,
`b_medication` text default NULL,
`b_medication_status` enum('not_answered') default NULL,
`opiates` enum('yes','no','not_answered') default NULL,
`o_medication` text default NULL,
`o_medication_status` enum('not_answered') default NULL,
`baclofen` enum('yes','no','not_answered') default NULL,
`bac_medication` text default NULL,
`bac_medication_status` enum('not_answered') default NULL,
`other_medication` text default NULL,
`other_medication_status` enum('not_answered') default NULL,
`alcohol` numeric default NULL,
`recreational_drugs` text default NULL,
`recreational_drugs_status` enum('not_answered') default NULL,
`clinical_trials` enum('yes','no','not_answered') default NULL,
`clinical_1` varchar(255) default NULL,
`clinical_1_date` date default NULL,
`form_type_history` enum('initial','update','no_change','not_answered') default NULL,
`stroke` enum('yes','no','not_answered') default NULL,
`brain_trauma` enum('yes','no','not_answered') default NULL,
`c_l_issues` enum('yes','no','not_answered') default NULL,
`epilepsy` enum('yes','no','not_answered') default NULL,
`o_neuro_conditions` enum('yes','no','not_answered') default NULL,
`n_conditions` varchar(255) default NULL,
`depression` enum('yes','no','not_answered') default NULL,
`o_p_conditions` enum('yes','no','not_answered') default NULL,
`p_conditions` varchar(255) default NULL,
`malignancy` enum('yes','no','not_answered') default NULL,
`m_type` varchar(255) default NULL,
`m_year` numeric default NULL,
`chemo` enum('yes','no','not_answered') default NULL,
`diabetes` enum('yes','no','not_answered') default NULL,
`hypertension` enum('yes','no','not_answered') default NULL,
`o_s_conditions` enum('yes','no','not_answered') default NULL,
`s_conditions` varchar(255) default NULL,
`notes` text default NULL,
`notes_status` enum('not_answered') default NULL,
PRIMARY KEY  (`CommentID`)
);
REPLACE INTO test_names (Test_name, Full_name, Sub_group) VALUES ('mef', 'Medical Evaluations Form', 1);
