CREATE TABLE `mri_parameter_form` (
`CommentID` varchar(255) NOT NULL default '',
                          `UserID` varchar(255) default NULL,
                          `Examiner` varchar(255) default NULL,
                          `Testdate` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                          `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL default 'Incomplete',
`Date_taken` date default NULL,
`Candidate_Age` varchar(255) default NULL,
`Window_Difference` varchar(255) default NULL,
`Scanner_Type` enum('siemens_64ch','seimens_20ch','ge_32ch','ge_8ch','philips_8ch','other') default NULL,
`Scanner_Type_other` varchar(255) default NULL,
`sedation` enum('Yes','No') default NULL,
`medication` enum('Yes','No','not_answered') default NULL,
`medication_specify` varchar(255) default NULL,
`t1_1_0_Scan_done` enum('No','Complete','Partial','not_answered') default NULL,
`t1_1_0_Comments` text default NULL,
`t1_1_0_Comments_status` enum('not_answered') default NULL,
`t1_0_8_Scan_done` enum('No','Complete','Partial','not_answered') default NULL,
`t1_0_8_Comments` text default NULL,
`t1_0_8_Comments_status` enum('not_answered') default NULL,
`t1_other_Scan_done` enum('No','Complete','Partial','not_answered') default NULL,
`t1_other_Comments` text default NULL,
`t2_1_0_Scan_done` enum('No','Complete','Partial','not_answered') default NULL,
`t2_1_0_Comments` text default NULL,
`t2_1_0_Comments_status` enum('not_answered') default NULL,
`t2_0_8_Scan_done` enum('No','Complete','Partial','not_answered') default NULL,
`t2_0_8_Comments` text default NULL,
`t2_0_8_Comments_status` enum('not_answered') default NULL,
`t2_other_Scan_done` enum('No','Complete','Partial','not_answered') default NULL,
`t2_other_Comments` text default NULL,
`flair_Scan_done` enum('No','Complete','Partial','not_answered') default NULL,
`flair_Comments` text default NULL,
`flair_Comments_status` enum('not_answered') default NULL,
`r2star_Scan_done` enum('No','Complete','Partial','not_answered') default NULL,
`r2star_Comments` text default NULL,
`r2star_Comments_status` enum('not_answered') default NULL,
`dti_2_0_Scan_done` enum('No','Complete','Partial','not_answered') default NULL,
`dti_2_0_Comments` text default NULL,
`dti_2_0_Comments_status` enum('not_answered') default NULL,
`dti_1_5_Scan_done` enum('No','Complete','Partial','not_answered') default NULL,
`dti_1_5_Comments` text default NULL,
`dti_1_5_Comments_status` enum('not_answered') default NULL,
`dti_other_Scan_done` enum('No','Complete','Partial','not_answered') default NULL,
`dti_other_Comments` text default NULL,
`fMRI_3_0_Scan_done` enum('No','Complete','Partial','not_answered') default NULL,
`fMRI_3_0_Number_Complete_Runs` varchar(255) default NULL,
`fMRI_3_0_Comments` text default NULL,
`fMRI_3_0_Comments_status` enum('not_answered') default NULL,
`fMRI_2_0_Scan_done` enum('No','Complete','Partial','not_answered') default NULL,
`fMRI_2_0_Number_Complete_Runs` varchar(255) default NULL,
`fMRI_2_0_Comments` text default NULL,
`fMRI_2_0_Comments_status` enum('not_answered') default NULL,
`fMRI_other_Scan_done` enum('No','Complete','Partial','not_answered') default NULL,
`fMRI_other_Comments` text default NULL,
PRIMARY KEY  (`CommentID`)
);
REPLACE INTO test_names (Test_name, Full_name, Sub_group) VALUES ('mri_parameter_form', 'MRI Parameter Form', 1);
