CREATE TABLE `nef_c` (
`CommentID` varchar(255) NOT NULL default '',
                          `UserID` varchar(255) default NULL,
                          `Examiner` varchar(255) default NULL,
                          `Testdate` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                          `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL default 'Incomplete',
`Date_taken` date default NULL,
`Candidate_Age` varchar(255) default NULL,
`Window_Difference` varchar(255) default NULL,
`tapping_done` enum('done','not_done','unable') default NULL,
`f_r_1` varchar(255) default NULL,
`f_l_1` varchar(255) default NULL,
`f_r_2` varchar(255) default NULL,
`f_l_2` varchar(255) default NULL,
`fe_r_1` varchar(255) default NULL,
`fe_l_1` varchar(255) default NULL,
`fe_r_2` varchar(255) default NULL,
`fe_l_2` varchar(255) default NULL,
`speech_done` enum('done','not_done') default NULL,
`speech_date` date default NULL,
`file_number` varchar(255) default NULL,
`file_name` varchar(255) default NULL,
`saccades_done` enum('done','not_done') default NULL,
`saccades_date` date default NULL,
`saccades` varchar(255) default NULL,
`antisaccades` varchar(255) default NULL,
`mri_done` enum('done','not_done') default NULL,
`mri_date` date default NULL,
`mri_filename` varchar(255) default NULL,
`medication` enum('yes','no','not_answered') default NULL,
`medication_detail` text default NULL,
`notes` text default NULL,
PRIMARY KEY  (`CommentID`)
);
REPLACE INTO test_names (Test_name, Full_name, Sub_group) VALUES ('nef_c', 'Array', 1);
