CREATE TABLE `svf_multi` (
`CommentID` varchar(255) NOT NULL default '',
                          `UserID` varchar(255) default NULL,
                          `Examiner` varchar(255) default NULL,
                          `Testdate` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                          `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL default 'Incomplete',
`Date_taken` date default NULL,
`Candidate_Age` varchar(255) default NULL,
`Window_Difference` varchar(255) default NULL,
`gender` enum('male','female','not_answered') default NULL,
`hand_preference` enum('right','left','ambidextrous','not_answered') default NULL,
`preferred_language` enum('english','french','other','not_answered') default NULL,
`highest_education` enum('elementary','high_school','post_secondary','declined','not_answered') default NULL,
`e_years` varchar(255) default NULL,
`a_english` varchar(255) default NULL,
`read_english` enum('yes','no','not_answered') default NULL,
`birth_place` varchar(255) default NULL,
`raised_place` varchar(255) default NULL,
`communication` enum('yes','no','not_answered') default NULL,
`communication_type` enum('gestures','writing','technology','other') default NULL,
`c_list` text default NULL,
`e_changes` enum('yes','no','not_answered') default NULL,
`clinical_trials` enum('yes','past','unknown','never') default NULL,
`clinical_1` varchar(255) default NULL,
`clinical_1_date` date default NULL,
`is_patient` enum('yes','no','not_answered') default NULL,
`onset_date` date default NULL,
`diagnosis_date` date default NULL,
`region_of_onset` varchar(255) default NULL,
`first_motor_onset` enum('right','left','both','unknown','0','1') default NULL,
`first_symptom` enum('weakness','fasciculations','atrophy','cramping','stiffness','other') default NULL,
`s_list` text default NULL,
`notes` text default NULL,
`moca` enum('done','not_done') default NULL,
`moca_date` date default NULL,
`type` enum('spoken','written') default NULL,
`visuospatial` varchar(255) default NULL,
`modification` enum() default NULL,
`naming_score` varchar(255) default NULL,
`attention_score` varchar(255) default NULL,
`language_score` varchar(255) default NULL,
`abstraction_score` varchar(255) default NULL,
`delayed_recall_score` varchar(255) default NULL,
`orientation_score` varchar(255) default NULL,
`total_score` varchar(255) default NULL,
PRIMARY KEY  (`CommentID`)
);
REPLACE INTO test_names (Test_name, Full_name, Sub_group) VALUES ('svf_multi', 'Array', 1);
